travis:
  secure:
    BINSTAR_TOKEN: kxJE1yIS76s0iO25OZndfKyo28PwxExh4zUo4AT6gjLUWo6VBnkrTmRShG8QApBYu1Zetfyp9+xlyqtUkfY9x+npU0i02TFgTr6dSTXPiLEwZCpbEwH730f/9wEYODM6ISEL4Zt4bLGyh//3m3x30q/8mM4C2FdASoG9QUWcbJBAjyuGAeCO94GADRmB7W1MjZ4p4M+5jUUUWJqq2UXAV06jqxdZo9jmSqhXHDXfn7MHubtaV0nDta+sGr8ptLhPaD8P8LMIFVPIGoR/PW+38a4zyELqMXf2GagCxb159m7Wt2+lWs+/q0CSQrI19dxsDRcRTK18jMJnEn+PLZhp+KiCCBhv42fIHD3+jo4k9E1myWvoVHidpCKr5qXNaashC+xmh5jVp1DRNqSLhz8NSRbqDhh/MGHIwU/tQZ9+TXXg4G5aprCWT8PJWsogp5FoaC9v258rDIf0n72JUThN+0dCQvYcFb9/Eh8KU2KbJEjWmjff9/BurL3JbAmz5UPBn3XUVvk5SOjWiBAN+L4Dw16veZNKB/6iWRyoeBuTiDiEiWa7HWpypT2WG5IU+kniFUjlX9nYa3cmtZY/KRAtgf7NYsHSTDLdxVruvNboZY5ClkhVv1zjImQJFAosntIVJdBswggrrTGFVQdxjyx6jaDwAPIeVwmd8RwIWezXoTE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
